Branch sebesu incident response
PagerDuty/incident-response-docs-ja pull request #12
Opened 2024-11-25 14:10 UTC by sebesu-pd

2025-02-12 05:29 UTC, jacopen-pd requested changes
ですます調に

2025-02-12 05:29 UTC, jacopen-pd commented on docs/oncall/being_oncall.md
> +* 「エスカレーションをためらってはならない。」問題の解決方法がわからない場合は、他の誰かを巻き込むことを恥ずかしいと思わないこと。同様に、他の誰かが助けを求めてきた場合、その人を軽蔑してはならない。
```suggestion
* 「エスカレーションをためらってはならない。」問題の解決方法がわからない場合は、他の誰かを巻き込むことを恥ずかしいと思わないでください。同様に、他の誰かが助けを求めてきた場合、その人を軽蔑してはなりません。
```

2025-02-12 11:35 UTC, pd-mhori reviewed
意味が通りづらく感じた箇所を中心にsuggest入れましたー。

2025-02-12 11:35 UTC, pd-mhori commented on docs/oncall/being_oncall.md
> +* 他のメンバーが希望し、あなたが対応できる場合は、1時間程度オンコールシフトをカバーすることを常に検討してください。私たちは皆、オンコールシフトの妨げとなるような生活があります。そして、いつか、あなたがオンコールシフトを交換しなければならない状況に陥り、遠方から来た友人と夜を過ごすことになるかもしれません。
エモめのチューニングsuggestです。

```suggestion
* 他のメンバーが希望し、あなたが対応できる場合は、1時間程度オンコールシフトをカバーすることを常に検討してください。私たちには誰しも、オンコールシフトに代えがたい生活があります。いつか、今度はあなたに代わって誰かがオンコールシフトを引き受けてくれたおかげで、遠方から来た友人と過ごせる夜が来るかもしれません。
```

2025-02-12 11:35 UTC, pd-mhori commented on docs/oncall/being_oncall.md
> +        * 夜間に行う必要のない戦術的な作業であるか？ 例えば、ディスク使用率が高水準値だが、十分な空き容量が残っており、傾向から差し迫った危機が迫っているわけではない場合など。より適切な時間（就業時間中または翌朝）までアラートを無視し、その時間帯に修正作業を行う。
「戦術的な作業」だとよくわからない感じがしたので、膨らませsuggestです。

```suggestion
        * 夜間対応は不要だが、先を見据えて行う必要のある作業か？ 例えば、ディスク使用率が高水準値だが、十分な空き容量が残っており、傾向から差し迫った危機が迫っているわけではない場合など。より適切な時間（就業時間中または翌朝）までアラートを無視し、その時間帯に修正作業を行う。
```

2025-02-12 11:35 UTC, pd-mhori commented on docs/oncall/being_oncall.md
> +        * ディスクがいっぱいになる、ログをローテーションすべき、うるさいアラート...
```suggestion
        * 一杯になるディスク、ローテーションすべきログ、過剰なアラートなど
```

2025-02-12 11:35 UTC, pd-mhori commented on docs/oncall/being_oncall.md
> +    * サービスオーナーは、常に自分たちの業務についてより詳しく知っています。特に、私たちのドキュメントやお客様のドキュメントに不足がある場合、関連チームとダブルチェックすることでミスを回避できます。二度測定して一度カットする - そして、対象分野の専門家（SME）にカットしてもらうのが最善である場合が多いです。
`Measure twice, cut once` はことわざなので、その意味合いで訳してしまったほうが良さそうです。

```suggestion
    * サービスオーナーは、常に自分たちの業務についてより詳しく知っています。特に、私たちのドキュメントやお客様のドキュメントに不足がある場合、関連チームとダブルチェックすることでミスを回避できます。後々のことを考えて、念には念を入れましょう - そして、対象分野の専門家（SME）にカットしてもらうのが最善である場合が多いです。
```

2025-02-12 11:35 UTC, pd-mhori commented on docs/oncall/being_oncall.md
> +* 何かをテストしたり、通知を発生させることが分かっているアクションを実行する場合は、テストを行っている間は「通知を取る」のが通例です。テストを行う間、次の1時間通知を取ることをオンコール担当者に知らせます。
「誰が」通知を取るのか書いたほうが意味が通りやすいかもです。

```suggestion
* 何かをテストしたり、通知を発生させることが分かっているアクションを実行する場合、テストを行っている間は自分で「通知を取る」のが通例です。テストを行う間、次の1時間は自分が通知を取ることをオンコール担当者に知らせます。
```

2025-02-12 11:35 UTC, pd-mhori commented on docs/oncall/being_oncall.md
> +    * 情報を見つけるのが難しい、あるいは不可能な場合は、それを書き留めてください。知識ベースとドキュメントを常に再構築し、改善してください。あなたの頭の中のWikiやコードベースが、現在の構成と一致しない場合は、冗長なリンクやポインタを追加してください。
`Add redundant links and pointers` よくわかんないすね、これ。多分こういうこと言いたいのかなあ。合ってるかわからないですが

```suggestion
    * 情報を見つけるのが難しい、あるいは不可能な場合は、それを書き留めてください。知識ベースとドキュメントを常に再構築し、改善してください。あなたの頭の中のWikiやコードベースが、現在の構成と一致しない場合は、情報を補う可能性のあるリソースへのリンクやポインタを追加してください。
```

2025-02-19 02:48 UTC, pd-mhori commented on docs/oncall/being_oncall.md
> +        * PagerDuty からのテキストメッセージや電話が [「おやすみモード」の設定を回避] できることを確認してください（https://support.pagerduty.com/main/lang-ja/docs/notification-phone-numbers）
リンクがワークするように

```suggestion
        * PagerDuty からのテキストメッセージや電話が [「おやすみモード」の設定を回避](https://support.pagerduty.com/main/lang-ja/docs/notification-phone-numbers) できることを確認してください
```

2025-02-19 03:45 UTC, merged